# Generated by Django 4.2.6 on 2023-10-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=250, verbose_name='Localização')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
            ],
        ),
    ]
